version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y zip unzip curl
  build:
    commands:
      - echo Build started on `date`
      - echo Reading the Repo...
  post_build:
    commands:
      - zip -qr aws-rm-backend.zip ./*
      - ls
      - aws s3 cp aws-rm-backend.zip s3://resources.cloudthat.com/dev/rm/
      - echo Build Finished on `date`
      - curl https://8hjl913gfh.execute-api.ap-south-1.amazonaws.com/dev/updateresource